FROM registry.gitlab.com/drz-docker-images/drz-botapplication-runner:latest
WORKDIR /app

COPY package*.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY src ./src

EXPOSE 5000


